name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports: [ '27017:27017' ]
        options: --quiet

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install server dependencies
      working-directory: ./server
      run: npm install

    - name: Run server tests
      working-directory: ./server
      run: npm test || echo "No tests yet"

    - name: Install client dependencies
      working-directory: ./client
      run: npm install

    - name: Build client
      working-directory: ./client
      run: npm run build
